export const CATALOGOS_EXPORTACION = [
  {
    id: "domicilios-fiscales",
    nombre: "Domicilios Fiscales",
    nombreSingular: "Domicilio Fiscal",
    cat: "CAT-032",
    descripcion: "Clasifica la condición fiscal del emisor o receptor.",
    endpoint: "/domicilios-fiscales",
    codigoNumerico: true,
    maxLength: null,
    placeholderCodigo: "Ej. 1",
    placeholderDescripcion: "Ej. Domiciliado",
    icono: "pi pi-map-marker",
  },
  {
    id: "incoterms",
    nombre: "Incoterms",
    nombreSingular: "Incoterm",
    cat: "CAT-031",
    descripcion: "Define las condiciones comerciales de la exportación.",
    endpoint: "/incoterms",
    codigoNumerico: false,
    maxLength: 2,
    placeholderCodigo: "Ej. 01",
    placeholderDescripcion: "Ej. EXW - En fábrica",
    icono: "pi pi-compass",
  },
  {
    id: "paises",
    nombre: "Países",
    nombreSingular: "País",
    cat: "CAT-020",
    descripcion: "Administra los países disponibles para exportación.",
    endpoint: "/paises",
    codigoNumerico: false,
    maxLength: 2,
    placeholderCodigo: "Ej. SV",
    placeholderDescripcion: "Ej. El Salvador",
    icono: "pi pi-globe",
  },
  {
    id: "recintos-fiscales",
    nombre: "Recintos Fiscales",
    nombreSingular: "Recinto Fiscal",
    cat: "CAT-027",
    descripcion: "Identifica las aduanas y recintos fiscales de salida.",
    endpoint: "/recintos-fiscales",
    codigoNumerico: false,
    maxLength: 2,
    placeholderCodigo: "Ej. 01",
    placeholderDescripcion: "Ej. Aduana Terrestre San Bartolo",
    icono: "pi pi-building",
  },
  {
    id: "regimenes",
    nombre: "Regímenes",
    nombreSingular: "Régimen",
    cat: "CAT-028",
    descripcion: "Gestiona los regímenes aduaneros aplicables.",
    endpoint: "/regimenes",
    codigoNumerico: false,
    maxLength: 8,
    placeholderCodigo: "Ej. 1000.000",
    placeholderDescripcion: "Ej. Exportación Definitiva, Régimen Común",
    icono: "pi pi-list",
  },
  {
    id: "tipos-documento-identificacion",
    nombre: "Tipos de Documento de Identificación",
    nombreSingular: "Tipo de Documento",
    cat: "CAT-022",
    descripcion: "Define los documentos de identificación aceptados.",
    endpoint: "/tipos-documento-identificacion",
    codigoNumerico: false,
    maxLength: 2,
    placeholderCodigo: "Ej. 13",
    placeholderDescripcion: "Ej. DUI",
    icono: "pi pi-id-card",
  },
  {
    id: "tipos-persona",
    nombre: "Tipos de Persona",
    nombreSingular: "Tipo de Persona",
    cat: "CAT-029",
    descripcion: "Clasifica a las personas naturales o jurídicas.",
    endpoint: "/tipos-persona",
    codigoNumerico: true,
    maxLength: null,
    placeholderCodigo: "Ej. 1",
    placeholderDescripcion: "Ej. Persona Natural",
    icono: "pi pi-users",
  },
  {
    id: "tipos-regimen",
    nombre: "Tipos de Régimen",
    nombreSingular: "Tipo de Régimen",
    cat: "CAT-033",
    descripcion: "Define la modalidad de régimen para la operación.",
    endpoint: "/tipos-regimen",
    codigoNumerico: false,
    maxLength: 5,
    placeholderCodigo: "Ej. EX-1",
    placeholderDescripcion: "Ej. Exportación Definitiva",
    icono: "pi pi-book",
  },
  {
    id: "tipos-transporte",
    nombre: "Tipos de Transporte",
    nombreSingular: "Tipo de Transporte",
    cat: "CAT-030",
    descripcion: "Administra los medios de transporte de la exportación.",
    endpoint: "/tipos-transporte",
    codigoNumerico: true,
    maxLength: null,
    placeholderCodigo: "Ej. 1",
    placeholderDescripcion: "Ej. TERRESTRE",
    icono: "pi pi-truck",
  },
  {
    id: "titulos-bienes",
    nombre: "Títulos de Bienes",
    nombreSingular: "Título de Bien",
    cat: "CAT-025",
    descripcion: "Indica el título bajo el cual se remiten los bienes.",
    endpoint: "/titulos-bienes",
    codigoNumerico: false,
    maxLength: 2,
    placeholderCodigo: "Ej. 01",
    placeholderDescripcion: "Ej. Propiedad",
    icono: "pi pi-box",
  },
];
